### ISSUE TITLE
How do you suppose displaying the content on an html template

### ISSUE THREAD

**Issue by ericel** [LeeHanYeong/django-quill-editor#12]
The editor works well, but displaying Quill content is kinda....
for and instance **object.content** will display something of this sort:
`<django_quill.fields.FieldQuill object at 0x7ff51c405190>
`
What are the suggestions here?

**Comment by ericel** [comment]
Should in case someone else comes across this, the django_quill object contains the attribute 'html'
You could use that to display the content of the editor.
`object.content.html`

That's what I am doing for now.

**Comment by LeeHanYeong** [comment]
I forgot to write in the document. thank you for telling me.

**Comment by ajayspicy07** [comment]
> I forgot to write in the document. thank you for telling me.

Object.content.html is showing
html script..
What should we use to show as WYSIWYT format??

**Comment by ajayspicy07** [comment]
> > I forgot to write in the document. thank you for telling me.
> 
> Object.content.html is showing
> html script..
> What should we use to show as WYSIWYT format??

{ objects.content.html|safe }

**Comment by LittleZabi** [comment]
object.content.html working great in a page but not in another page I don't know why. when I remove .html then it's showing the not formatted content with some rough data.

**Comment by mbosoft** [comment]
Fucking plugin 🤮🤮🤮🤮🤮🤮🤮🤮🤮
