### ISSUE TITLE
Dumpdata causes bad fixture format

### ISSUE THREAD

**Issue by michaldyczko** [LeeHanYeong/django-quill-editor#15]
Fixture created by `python manage.py dumpdata` causes error, because QuillField is badly serialized. It can be solved by adding:

```   
def value_to_string(self, obj):
    value = self.value_from_object(obj)
    return self.get_prep_value(value)
```

to QuillField.

**Comment by LeeHanYeong** [comment]
Merged c6b287739bbbf34105ceaf797e6fd1538082f0d4
