### ISSUE TITLE
Unpacking the form fields?

### ISSUE THREAD

**Issue by rosalesnikho** [LeeHanYeong/django-quill-editor#25]
Instead of using 
```
<form action="" method="POST">{% csrf_token %}
    {{ form.content }}
</form>
```
What's the recommended method of creating custom inputs? Example below.

```
<form action="" method="POST">
    {% csrf_token %}
   <input type="text" name="{% form.title %}">
</form>
```

**Comment by brian101co** [comment]
Check out this tutorial from Simpleisbetterthancomplex. I think it is what you are looking for.

https://simpleisbetterthancomplex.com/article/2017/08/19/how-to-render-django-form-manually.html

**Comment by rosalesnikho** [comment]
@brian101co - thank you. That's a really good write-up actually. It does answer my question perfectly.
