### ISSUE TITLE
[feature] make QuillField inherit JSONField

### ISSUE THREAD

**Issue by void-witch** [LeeHanYeong/django-quill-editor#26]
since QuillField stores text in the database directly as json-encoded text, it would be better to store it as a [JSONField](https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.JSONField). every major db backend supports the JSONField, so switching will not only be more idiomatic, but will also inform the db backend to apply any optimizations to speed up queries

~~i think the change would be pretty simple~~ after several hours of trying, i have realized it is absolutely not simple. i thought i could implement this on my own, but that is clearly not the case haha

**Comment by 3n-k1** [comment]
i ended up finding it shortly after writing this
