### ISSUE TITLE
QuillParseError: Failed to parse value(random string). Django Admin

### ISSUE THREAD

**Issue by brian101co** [LeeHanYeong/django-quill-editor#28]
Hello,

I am trying to integrate the QuillField() into the Django admin. However, when I change the model from textField to QuillField(), I get a QuillParseError whenever I try to edit existing objects in the Django admin. 

How would you resolve this error?

**Comment by brian101co** [comment]
Figured out the issue. Needed to do a data migration.

**Comment by gdudhatraTBH** [comment]
what kind of migration applied?
Can please explain with a short example?

**Comment by brian101co** [comment]
> what kind of migration applied?
> 
> Can please explain with a short example?

I wrote about here: [Data Migrations with Django](https://engineertodeveloper.com/django-data-migrations/)
