### ISSUE TITLE
Docs didn't say to include the tag in the form.

### ISSUE THREAD

**Issue by XtremeGood** [LeeHanYeong/django-quill-editor#33]
I was looking at the docs but I thing it's missed to be told that  ` {% include 'django_quill/media.html' %}` is to be included. I wasted lot of time on this.

**Comment by cdesch** [comment]
It says it here in the [readme.md in 2. Form](https://github.com/LeeHanYeong/django-quill-editor/blob/master/README.md#2-form), but it could be added to [docs form page](https://django-quill-editor.readthedocs.io/en/latest/pages/using-as-form.html)

**Comment by cdesch** [comment]
I added a fix for the docs in [PR#34](https://github.com/LeeHanYeong/django-quill-editor/pull/34). @LeeHanYeong will need to update or republish the docs https://django-quill-editor.readthedocs.io/

**Comment by XtremeGood** [comment]
Also can you attach functionality for file upload? I know it doesn't exist in quill js but more of less one can just insert additional handler and a font-awesome file upload icon.

**Comment by cdesch** [comment]
> Also can you attach functionality for file upload? I know it doesn't exists in quill.js but more of less one can just insert additional handler and a font-awesome file upload icon.

That is a little outside of my domain and not something quill supports. If you want to add it as a feature of this library in addition to quill, I encourage you to make a PR to add it.

**Comment by XtremeGood** [comment]
@cdesch  ok , I will try as soon as I get some free time .

**Comment by LeeHanYeong** [comment]
@cdesch @XtremeGood 
Thank you for adding content to the document. This content has been updated to version 0.1.18.
