### ISSUE TITLE
AttributeError 'NoneType' object has no attribute 'json_string'

### ISSUE THREAD

**Issue by lucaswatterson** [LeeHanYeong/django-quill-editor#38]
Initialized a new project this evening and installed django-quill-editor as per usual.  When I open the associated CreateView template, I get...

![issue](https://user-images.githubusercontent.com/1297951/107469195-e9327d80-6b2e-11eb-9db4-9e76a4af0270.PNG)

Funny thing is, the quill editor loads correctly in the UpdateView template.  The following text is strangely already in the editor...

![issue_2](https://user-images.githubusercontent.com/1297951/107469526-7ece0d00-6b2f-11eb-89e5-c781562f6eee.PNG)

I've double and triple checked that the model, view, and template are set-up correctly.

EDIT

Realized it might help to add that I am also using django-crispy-forms.

**Comment by afd57** [comment]
> Initialized a new project this evening and installed django-quill-editor as per usual. When I open the associated CreateView template, I get...
> 
> ![issue](https://user-images.githubusercontent.com/1297951/107469195-e9327d80-6b2e-11eb-9db4-9e76a4af0270.PNG)
> 
> Funny thing is, the quill editor loads correctly in the UpdateView template. The following text is strangely already in the editor...
> 
> ![issue_2](https://user-images.githubusercontent.com/1297951/107469526-7ece0d00-6b2f-11eb-89e5-c781562f6eee.PNG)
> 
> I've double and triple checked that the model, view, and template are set-up correctly.
> 
> EDIT
> 
> Realized it might help to add that I am also using django-crispy-forms.

Hello, I faced same error message. I downgraded to 0.1.16 version. It works well.

```bash
pip install django-quill-editor==0.1.16
```

**Comment by lucaswatterson** [comment]
@afd57 Thanks, I came to that solution as well.  I'll leave this open for @LeeHanYeong to see.  

I was able to remove the .json in forms.py to get the most recent version working, but obviously that may have unintended consequences.  Thanks again.

**Comment by afd57** [comment]
> @afd57 Thanks, I came to that solution as well. I'll leave this open for @LeeHanYeong to see.
> 
> I was able to remove the .json in forms.py to get the most recent version working, but obviously that may have unintended consequences. Thanks again.

I got you. :) You are welcome.

**Comment by cdesch** [comment]
@void-witch Can you take a look at this? I'm hitting the same error with version `0.1.19` on it appears to be this [line](https://github.com/LeeHanYeong/django-quill-editor/blob/f867a96d0b0f5a2554f000b5eb81637152184823/django_quill/forms.py#L17) on [this commit](https://github.com/LeeHanYeong/django-quill-editor/commit/a362dcad435649fe883702532d93df19b0ba020b) 

I think this issue may be related to the work that was merged recently and [PR#36](https://github.com/LeeHanYeong/django-quill-editor/pull/36).

**Comment by void-witch** [comment]
yup, this was an issue i missed, my bad. you have two ways to fix this:

1) change [line 17 of forms.py](https://github.com/LeeHanYeong/django-quill-editor/blob/master/django_quill/forms.py#L17) to be something like `return value.json_string if value else None`

2) install the json-field branch from [@cobang's fork](https://github.com/LeeHanYeong/django-quill-editor/pull/36)

i recommend option 2, until the pull request is merged. the fork fixes a lot of things i missed

**Comment by cdesch** [comment]
that fork in [PR#35](https://github.com/LeeHanYeong/django-quill-editor/pull/35) was pulled into the master but the PR is still open. Can you make a new PR to fix the line?

@LeeHanYeong can you close the PR requests?

**Comment by cdesch** [comment]
@void-witch any luck?

**Comment by void-witch** [comment]
@cdesch nothing i can do on my end. you can either edit the file, or point your dependencies to the fork

**Comment by cdesch** [comment]
I made the change and I'll submit a [PR#41](https://github.com/LeeHanYeong/django-quill-editor/pull/41)

The [JSONField was introduced in Django 3.1](https://docs.djangoproject.com/en/3.1/releases/3.1/#jsonfield-for-all-supported-database-backends) and makes this addition a breaking change for Django project versions < 3.1.x

**Comment by cdesch** [comment]
@lucaswatterson This issue can be resolved and closed with the recent release of `0.1.21`.

**Comment by lucaswatterson** [comment]
Thank you!

**Comment by cdesch** [comment]
@lucaswatterson You're welcome. Please close the issue.
