### ISSUE TITLE
Migrating HTML

### ISSUE THREAD

**Issue by djpeacher** [LeeHanYeong/django-quill-editor#44]
When I change an existing field type to `QuillField` it fails because it is expecting its value to be in the delta/html format `{"delta": "...", "html": "..."}`, but my current data is just raw HTML. Does anyone have any tips on how to migrate this data?

**Comment by hert22** [comment]
This documentation has been helping me a lot with QuillField and Quill in databases. [https://django-quill-editor.readthedocs.io/en/latest/index.html](url)

**Comment by djpeacher** [comment]
Thanks, but the documentation doesn't seem to have anything related to migrating existing data.

**Comment by LeeHanYeong** [comment]
A migration command has been added to the already used CharField or TextField.
```
python manage.py convert_to_quill {app_name} {model_name} {field_name}
```

https://django-quill-editor.readthedocs.io/en/latest/pages/migrating-to-quillfield.html
