### ISSUE TITLE
QuillField not showing in django admin

### ISSUE THREAD

**Issue by brunocpradom** [LeeHanYeong/django-quill-editor#51]
I'm working with Django 3.1.8
models.py
```
class UUIDModel(models.Model):
    class Meta:
        abstract = True

    id = UUIDPrimaryKeyField()
    
class Setup(UUIDModel):
    name = models.CharField(max_length = 255, verbose_name = "Nome")
    content = QuillField()
```
admin.py
```
@admin.register(Setup)
class SetupAdmin(admin.ModelAdmin):
    pass
```
I made the migrations , migrate, all the proccess.
The label content appear in the admin but has no field to write....

**Comment by LeeHanYeong** [comment]
Quill.js does not work in IE. Which browser are you using?

**Comment by brunocpradom** [comment]
Chrome

**Comment by tigrettin** [comment]
Having the same issue here.

It all works fine on my local computer, but when in production, QuillFileds are invisible on admin panel – only labels appear.

When inspecting the admin page on Chrome, I see such errors on the console:

```
GET https://mysite.com/static/django_quill/django_quill.css net::ERR_ABORTED 404 (Not Found)

GET https://andcetin.com/static/django_quill/django_quill.js net::ERR_ABORTED 404 (Not Found)

Uncaught ReferenceError: QuillWrapper is not defined
    at (index):261:27
    at (index):263:11
```

Somehow, **django_quill.css** and **django_quill.js** don't get loaded. I can't figure out why it works on my local project which has exactly the same setup, except that on local I use python 3.9/Django 4.0.1 while in production, it's v3.8/4.0.2.

Another difference is that, in production, **django_quill** folder is under `myenv/lib/python3.8/site-packages` directory.

On my computer, there is no **django_quill** folder under `myenv/lib/python3.9/site-packages/`. In fact, there is such folder at all anywhere on my drive, nor the related **django_quill.css** or **django_quill.js** files.

By the way, I had no problem while migrating from old TextField's or viewing the content on the templates.

Any suggestion or feedback will be welcomed and greatly appreciated.

Thank you.
