### ISSUE TITLE
Should support inital value

### ISSUE THREAD

**Issue by ericel** [LeeHanYeong/django-quill-editor#6]
Have you considered adding an initial value placeholder?

With what you have now, I doubt it will work with editing pages where there's suppose to be some initial value that is to be displayed on the editor.

**Comment by LeeHanYeong** [comment]
Does it mean the placeholder of the input tag?
If it means modifying `forms.ModelForm`, it works fine.
I haven't tested the `initial_data` in `forms.Form`. Did you mention this?

The example below is a normal update view function and html in action.

```python
# views.py
form = QuillPostModelForm(instance=post)
```

```django
<!-- template -->
{% include 'django_quill/media.html' %}
<form action="" method="POST">{% csrf_token %}
    {{ form.content }}
    <button type="submit" class="btn btn-block mt-1">Update Post</button>
</form>
```

**Comment by LeeHanYeong** [comment]
Does it mean the placeholder of the input tag?
If it means modifying `forms.ModelForm`, it works fine.
I haven't tested the `initial_data` in `forms.Form`. Did you mention this?

The example below is a update view function and html.
Thank you for your review

```python
# views.py
form = QuillPostModelForm(instance=post)
```

```django
<!-- template -->
{% include 'django_quill/media.html' %}
<form action="" method="POST">{% csrf_token %}
    {{ form.content }}
    <button type="submit" class="btn btn-block mt-1">Update Post</button>
</form>
```

**Comment by ericel** [comment]
I was trying to use it with a normal form(forms.Form). Probably why it wasn't working.

**Comment by LeeHanYeong** [comment]
I updated the new version to apply the initial value of forms.Form
Please get the 0.1.5 version again and try again.
Also updated the relevant example code.

> **In the sample directory**
view: `posts.views.quill_post_normal_form_initial_view`
template: `templates/posts/quillpost_normal_form.html`
url: `/posts/normal/`
