### ISSUE TITLE
Mention Django version support in README & Docs

### ISSUE THREAD

**Issue by TareqMonwer** [LeeHanYeong/django-quill-editor#64]
Hi!
Thank you for your effort for managing this package. I came across this yesterday and I found django-quill0editor is not working in Django 3.2 (to be specific, in template files, {{ obj.content.html|safe }} doesn't work, it throws some parsing error.) and I didn't even notice that support for Django 3.2 is not mentioned anywhere.

Is it possible to upgrade the package or at-least mention django supported version in the readme & docs?
Thanks.

**Comment by LeeHanYeong** [comment]
Hello. This library is being developed based on Django 3.2 :)
Let us know what error you're getting and we'll review it.
*If a model previously used as TextField or CharField is migrated to QuillField, it may not work properly.
