### ISSUE TITLE
Doesn't work after last update

### ISSUE THREAD

**Issue by mlalyko** [LeeHanYeong/django-quill-editor#65]
Hey, after last update, I can't add new data in admin panel. In some cases, I can't see the quill field, and in another cases, text from form doesn't save and assert alert.

I tried to downgrade to 0.1.22 and always have been okay.

**Comment by LeeHanYeong** [comment]
There was an error in admin not loading static files.
It was fixed in 0.1.25.
Thanks for the report :)
