### ISSUE TITLE
How can I override default settings?

### ISSUE THREAD

**Issue by nittolese** [LeeHanYeong/django-quill-editor#7]
I would like to avoid my user to upload Images while using editor.
How can I override these settings in [config.py](https://github.com/LeeHanYeong/django-quill-editor/blob/master/django_quill/config.py)?

**Comment by LeeHanYeong** [comment]
I haven't made it yet, but I'll work on the next feature.
Thank you for reporting the issue :)

**Comment by kandrokae** [comment]
Hitting the same issue, any solution/update coming up?

**Comment by LeeHanYeong** [comment]
@nittolese @kandrokae 
See this [section](https://github.com/LeeHanYeong/django-quill-editor#change-toolbar-menus) of the article.

**Comment by kandrokae** [comment]
thank you!
