### ISSUE TITLE
QuillField not showing in django admin

### ISSUE THREAD

**Issue by tigrettin** [LeeHanYeong/django-quill-editor#77]
I know this has been asked before #51, but the owner closed the issue without providing any feedback.

Quill editor v0.1.40 works fine on my local computer, but when in production, QuillFileds are invisible on admin panel – only labels appear:

<img src="https://i.ibb.co/vmM3gpG/Screen-Shot-2022-03-09-at-1-15-26-PM.png" alt="Screen-Shot-2022-03-09-at-1-15-26-PM" border="0">

When inspecting the admin page on Chrome, I see such errors on the console:

```
GET https://mysite.com/static/django_quill/django_quill.css net::ERR_ABORTED 404 (Not Found)

GET https://mysite.com/static/django_quill/django_quill.js net::ERR_ABORTED 404 (Not Found)

Uncaught ReferenceError: QuillWrapper is not defined
    at (index):261:27
    at (index):263:11
```

**django_quill.css** and **django_quill.js** fail to load. I can't figure out why it works on my local project which has the same setup, except that on local I use python 3.9/Django 4.0.1 while in production, it's v3.8/4.0.2.

Another difference is that, in production, **django_quill** folder is under `myenv/lib/python3.8/site-packages/` directory.

On my computer, there is no **django_quill** folder under `myenv/lib/python3.9/site-packages/`. In fact, there is no such folder anywhere on my drive, nor the related **django_quill.css** or **django_quill.js** files.

I have no problem while migrating from old TextField's, or viewing the content on the templates.

Any suggestion or feedback will be welcomed and greatly appreciated.

Thank you.

**Comment by Kasperror** [comment]
Did you run collectstatic using production settings (in contrast to development) in production? This seems like a common problem not really related to this package - confirm the needed files are indeed in the served directory if not move them there

**Comment by tigrettin** [comment]
Thank you for the reply, though I already did collectstatic.

**Comment by Kasperror** [comment]
do you use multiple settings files like prod_settings.py and dev_settings.py? This could be a problem due to different STATIC_ROOTs  - thats why I asked abut production settings specifically. There also might be a problem with with your server configuration or STATIC_ROOT - both ways the problem doesn't lay in the package thus the issue should be closed I think

**Comment by tigrettin** [comment]
> do you use multiple settings files like prod_settings.py and dev_settings.py? This could be a problem due to different STATIC_ROOTs - thats why I asked abut production settings specifically. There also might be a problem with with your server configuration or STATIC_ROOT - both ways the problem doesn't lay in the package thus the issue should be closed I think

Hello again, you are right. On my dev settings, static configuration was as follows:

```
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
```

Whereas on production:

```
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'static/root'
```

Which was a mistake, of course. STATICFILES_DIRS shouldn't be present on production. So I changed it to:

```
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static/'
```

and ran _collectstatic_. Now it works fine.

Thank you Kasperror!
