### ISSUE TITLE
Adding a plugin

### ISSUE THREAD

**Issue by gfunch** [LeeHanYeong/django-quill-editor#89]
Hi, 
This is a great project and it has been very useful in an application I am developing.

I am interested in incorporating a Quill plugin (quill-comment: https://www.npmjs.com/package/quill-comment).

Can you please provide some guidance on how this can be done and accessed through django-quill?

Thank you!

**Comment by gfunch** [comment]
I found a solution.

**Comment by theinvestigamer** [comment]
> 

What was the solution?
