### ISSUE TITLE
TemplateDoesNotExist exception on a new project

### ISSUE THREAD

**Issue by nittolese** [LeeHanYeong/django-quill-editor#9]
Hi, I tried to install django-quill-editor via pip in a new project but I keep seeing this in admin when I try to add a new `QuillPost`

![image](https://user-images.githubusercontent.com/25707285/80470260-0a303600-8942-11ea-9722-538fcc79d038.png)

**Comment by LeeHanYeong** [comment]
Did you add 'django_quill' to INSTALLED_APPS?

```
# settings.py
INSTALLED_APPS = [
    ...
    'django_quill',
]
```

**Comment by nittolese** [comment]
Yup, I've added both 'django_quill' and an example app to INSTALLED_APPS, but I keep getting that error.

**Comment by skilaren** [comment]
It seems that there is no templates files loaded within ` pip install ` for some reason

**Comment by skilaren** [comment]
You can fix it by placing **templates** folder from repository to the folder specified in your project settings in DIRS in TEMPLATES and set the `FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'`

**Comment by LeeHanYeong** [comment]
@skilaren Thanks for the advice
@nittolese 
Fixed a bug where static files were not included in the distribution package.
If you upgrade to version 0.10.0, it works normally.
`pip install django-quill-editor --upgrade`
